### --------------------------------------------------------------------------------------------------------------------
GET http://{{host}}/vtag/device/all

### --------------------------------------------------------------------------------------------------------------------
POST http://{{host}}/vtag/device/pair
Authorization: Bearer {{vtag_token}}
Content-Type: application/json

{"platform_id": "f7db01c2-991c-4a68-a271-c6ef4406aaa9"}



### --------------------------------------------------------------------------------------------------------------------
POST http://{{host}}/vtag/device/unpair
Authorization: Bearer dfb4d7aa-08f0-4bbf-addb-525dd74b5f70
#{{vtag_token}}
Content-Type: application/json

{"platform_id": "7b762bf8-f157-467c-8f3d-a9d1eb342e35"}



### --------------------------------------------------------------------------------------------------------------------
GET http://{{host}}/vtag/device/list
Authorization: Bearer 82826b06-778d-456a-8bbf-ff83c3d375bb
#{{vtag_token}}



### --------------------------------------------------------------------------------------------------------------------
GET http://{{host}}/vtag/device/history
    ?device_id=7b762bf8-f157-467c-8f3d-a9d1eb342e35
    &from=2021-03-31T00:00:00
    &to=2021-12-31T12:59:59
Authorization: Bearer {{vtag_token}}



### --------------------------------------------------------------------------------------------------------------------
PUT http://{{host}}/vtag/device/name
Authorization: Bearer {{vtag_token}}
Content-Type: application/json

{
    "name": "Name 1",
    "platform_id": "7b762bf8-f157-467c-8f3d-a9d1eb342e35"
}



### --------------------------------------------------------------------------------------------------------------------
POST http://{{host}}/vtag/device/history
Authorization: Bearer {{vtag_token}}
Content-Type: application/json

{
    "device_id": "d61e77a7-6794-40ba-95e9-c7900e4e5f8e",
    "from": 0,
    "to": 10000000000
}



### --------------------------------------------------------------------------------------------------------------------
GET http://{{host}}/vtag/device/messages
    ?device_id=7b762bf8-f157-467c-8f3d-a9d1eb342e35
    &offset=0
    &limit=100
Authorization: Bearer #{{vtag_token}}



### --------------------------------------------------------------------------------------------------------------------
GET http://{{host}}/vtag/device/geo/7e1fcfca-9f7e-44b0-85d8-718036b58b9e
Authorization: Bearer ad8ef77e-5058-48f9-a2c8-bce0146c2671 #{{vtag_token}}

### --------------------------------------------------------------------------------------------------------------------
POST http://{{host}}/vtag/device/geo/7e1fcfca-9f7e-44b0-85d8-718036b58b9e
Authorization: Bearer e384cb8c-8101-43cb-a7ee-47e7c4f7f6fe #{{vtag_token}}
Content-Type: application/json

[{"name": "Ho Tay", "lat": 21.068889, "lon": 105.812353, "radius": 100}]



### --------------------------------------------------------------------------------------------------------------------
DELETE http://{{host}}/vtag/device/geo/7b762bf8-f157-467c-8f3d-a9d1eb342e35
Authorization: Bearer {{vtag_token}}


### --------------------------------------------------------------------------------------------------------------------
GET http://{{host}}/vtag/device/config/9ee7c288-f54e-4855-a8b5-138ca1c53f0a
Authorization: Bearer 918254e4-76b9-4cdd-893e-836a77792164 #{{vtag_token}}

### --------------------------------------------------------------------------------------------------------------------
POST http://{{host}}/vtag/device/config/9ee7c288-f54e-4855-a8b5-138ca1c53f0a
Authorization: Bearer 918254e4-76b9-4cdd-893e-836a77792164 #{{vtag_token}}
Content-Type: application/json

{
    "mode": 2,
    "points": [
        {
            "start_time": "6:00",
            "end_time": "21:00",
            "cycle": "5"
        },
        {
            "start_time": "6:00",
            "end_time": "21:00",
            "cycle": 5
        }
    ]
}
