### --------------------------------------------------------------------------------------------------------------------
POST http://{{host}}/vtag/device/pair
Authorization: Bearer {{vtag_token}}
Content-Type: application/json

{"platform_id": "d61e77a7-6794-40ba-95e9-c7900e4e5f8e"}

###{"platform_id": "d86c8f22-e026-440f-bc17-ca77cee811c2"}

### 200: {"code": 0, "message": "Paired device successfully!"}
### 502: {"code": 1, "message": "Couldn't pair device!"}



### --------------------------------------------------------------------------------------------------------------------
GET http://{{host}}/vtag/device/list
Content-Type: application/json
Authorization: Bearer {{vtag_token}}

### 200: {"code": 0, "message": "Okie dokie!", "data": [{
###     "id": 1, "platform_device_id": "", "latitude": 123.123, "longitude": 123.123, "status": "Real-time", "accuracy": 40,
###     "geo-fencing": 0, "uptime": "2021-01-31T12:59:59", "battery": 95, "name": "Tern cua device"
### }]}




### --------------------------------------------------------------------------------------------------------------------
GET http://{{host}}/vtag/device/history
    ?device_id=7b762bf8-f157-467c-8f3d-a9d1eb342e35
    &from=2021-03-31T00:00:00
    &to=2021-04-10T12:59:59
Authorization: Bearer {{vtag_token}}
Content-Type: application/json



### --------------------------------------------------------------------------------------------------------------------
PUT http://{{host}}/vtag/device/name
Authorization: Bearer {{vtag_token}}
Content-Type: application/json

{
    "name": "Name 1",
    "platform_id": "7b762bf8-f157-467c-8f3d-a9d1eb342e35"
}

### 200 {"code": 0, "message": "Changed device's name successfully!"}
### 417 {"code": 1, "message": "Couldn't update device's name!"}
### 500 {"code": 1, "message": "Couldn't update device's name!"}



### --------------------------------------------------------------------------------------------------------------------
POST http://{{host}}/vtag/device/history
Authorization: Bearer {{vtag_token}}
Content-Type: application/json

{
    "device_id": "d61e77a7-6794-40ba-95e9-c7900e4e5f8e",
    "from": 0,
    "to": 10000000000
}



### --------------------------------------------------------------------------------------------------------------------
POST http://{{host}}/vtag/device/unpair
Authorization: Bearer {{vtag_token}}
Content-Type: application/json

{
    "device_id": "d61e77a7-6794-40ba-95e9-c7900e4e5f8e"
}



### --------------------------------------------------------------------------------------------------------------------
GET http://{{host}}/vtag/device/messages
    ?device_id=7b762bf8-f157-467c-8f3d-a9d1eb342e35
    &offset=0
    &limit=100
Authorization: Bearer {{vtag_token}}
Content-Type: application/json

