### --------------------------------------------------------------------------------------------------------------------
POST http://{{host}}/vtag/device/pair
Authorization: Bearer {{vtag_token}}
Content-Type: application/json

{"platform_id": "7b762bf8-f157-467c-8f3d-a9d1eb342e35"}



### --------------------------------------------------------------------------------------------------------------------
POST http://{{host}}/vtag/device/unpair
Authorization: Bearer {{vtag_token}}
Content-Type: application/json

{"platform_id": "7b762bf8-f157-467c-8f3d-a9d1eb342e35"}



### --------------------------------------------------------------------------------------------------------------------
GET http://{{host}}/vtag/device/list
Content-Type: application/json
Authorization: Bearer {{vtag_token}}



### --------------------------------------------------------------------------------------------------------------------
GET http://{{host}}/vtag/device/history
    ?device_id=7b762bf8-f157-467c-8f3d-a9d1eb342e35
    &from=2021-03-31T00:00:00
    &to=2021-12-31T12:59:59
Authorization: Bearer {{vtag_token}}



### --------------------------------------------------------------------------------------------------------------------
PUT http://{{host}}/vtag/device/name
Authorization: Bearer {{vtag_token}}
Content-Type: application/json

{
    "name": "Name 1",
    "platform_id": "7b762bf8-f157-467c-8f3d-a9d1eb342e35"
}



### --------------------------------------------------------------------------------------------------------------------
POST http://{{host}}/vtag/device/history
Authorization: Bearer {{vtag_token}}
Content-Type: application/json

{
    "device_id": "d61e77a7-6794-40ba-95e9-c7900e4e5f8e",
    "from": 0,
    "to": 10000000000
}



### --------------------------------------------------------------------------------------------------------------------
GET http://{{host}}/vtag/device/messages
    ?device_id=7b762bf8-f157-467c-8f3d-a9d1eb342e35
    &offset=0
    &limit=100
Authorization: Bearer {{vtag_token}}
Content-Type: application/json

