### --------------------------------------------------------------------------------------------------------------------
GET http://{{host}}/vtag/test/mqtt/sub
    ?id=691e700f-9b1c-477f-a2fc-3699de6e3d15
    &subtopic=events




### --------------------------------------------------------------------------------------------------------------------
POST https://ap1.unwiredlabs.com/v2/process.php
Content-Type: application/json

{
    "token": "{{token}}",
    "radio": "nbiot",
    "address": 1,
    "mcc": 452,
    "mnc": 4,
    "cells": [
        {"cid": 75430933, "lac": 43300, "psc": 0}
    ],
    "wifi": [
        {"signal": -59, "bssid": "E6:A6:B2:0F:82:73"},
        {"signal": -66, "bssid": "3C:7C:3F:40:B4:68"},
        {"signal": -70, "bssid": "C0:4A:00:0C:8B:A2"},
        {"signal": -78, "bssid": "7C:8B:CA:DF:9D:E4"},
        {"signal": -83, "bssid": "D4:2C:3D:29:18:0D"},
        {"signal": -89, "bssid": "3C:15:FB:42:DE:0C"},
        {"signal": -91, "bssid": "10:2F:6B:BB:1C:33"}
    ]
}

### "status": "ok", "balance": 4656, "lat": 21.066706,   "lon": 105.811164,   "accuracy": 2500
### "status": "ok", "balance": 4655, "lat": 21.06757812, "lon": 105.81127031, "accuracy": 40



### --------------------------------------------------------------------------------------------------------------------
POST https://ap1.unwiredlabs.com/v2/process.php
Content-Type: application/json

{
    "token": "{{token}}",
    "radio": "nbiot",
    "address": 1,
    "mcc": 452,
    "mnc": 4,
    "cells": [
        {"cid": 75430933, "lac": 43300, "psc": 0}
    ],
    "wifi": [
    ]
}

### "status": "ok", "balance": 4656, "lat": 21.066706,   "lon": 105.811164,   "accuracy": 2500
### "status": "ok", "balance": 4655, "lat": 21.06757812, "lon": 105.81127031, "accuracy": 40



### wifi cell ----------------------------------------------------------------------------------------------------------
POST http://{{host}}/vtag/device/test
Content-Type: application/json

{
    "Type": "DWFC",
    "Conn": "nbiot",
    "Cell": [
        {"CID": 75430933, "LAC": 43300, "MCC": 452, "MNC": 4, "SS": -93}
    ],
    "APs": [
        {"SS": -59, "MAC": "E6:A6:B2:0F:82:73"},
        {"SS": -66, "MAC": "3C:7C:3F:40:B4:68"},
        {"SS": -70, "MAC": "C0:4A:00:0C:8B:A2"},
        {"SS": -78, "MAC": "7C:8B:CA:DF:9D:E4"},
        {"SS": -83, "MAC": "D4:2C:3D:29:18:0D"},
        {"SS": -89, "MAC": "3C:15:FB:42:DE:0C"},
        {"SS": -91, "MAC": "10:2F:6B:BB:1C:33"}
    ]
}



### GPS ----------------------------------------------------------------------------------------------------------------
POST http://{{host}}/vtag/device/test
Content-Type: application/json

{
    "Type": "DPOS",
    "Conn": "nbiot",
    "Ver": "7.2",
    "Lat": 21.068147769858182,
    "Lon": 105.81206979664238,
    "TS": "2021-03-24 14-33-23"
}



### SOS ----------------------------------------------------------------------------------------------------------------
POST http://{{host}}/vtag/device/test
Content-Type: application/json

{
    "Type": "DSOS",
    "Conn": "nbiot",
    "Cell": [{"CID": 75430933, "LAC": 43300, "MCC": 452, "MNC": 4, "SS": -95}],
    "APs": [
        {"SS": -58, "MAC": "B0:95:75:6B:B0:B7"},
        {"SS": -67, "MAC": "A0:F3:C1:CF:32:F6"},
        {"SS": -79, "MAC": "C0:A5:DD:14:67:B2"},
        {"SS": -84, "MAC": "00:1D:0F:CB:35:84"},
        {"SS": -89, "MAC": "68:FF:7B:21:9F:50"},
        {"SS": -90, "MAC": "AC:84:C6:B4:40:5A"},
        {"SS": -92, "MAC": "9C:65:EE:BB:68:AF"},
        {"SS": -94, "MAC": "B4:EE:B4:61:2F:FA"},
        {"SS": -95, "MAC": "D8:07:B6:EE:6F:C3"}
    ]
}

### SMS
POST http://{{host}}/vtag/test/sms
    ?recipient=0365819777
    &content="Hello world"


### fcm ----------------------------------------------------------------------------------------------------------------
POST http://{{host}}/vtag/test/fcm
Content-Type: text/plain
#Accept-Language: en-US

some content


### fcm ----------------------------------------------------------------------------------------------------------------
POST http://{{host}}/vtag/test/query
Content-Type: text/plain
Accept-Language: en-US

some content


