### --------------------------------------------------------------------------------------------------------------------
POST http://{{host}}/vtag/user/otp/register
Content-Type: application/json

{"type": "phone", "value": "84365819777"}



### Register new account -----------------------------------------------------------------------------------------------
POST http://{{host}}/vtag/user/register
Content-Type: application/json

{"phone": "0365819777", "password": "test"}


### check token --------------------------------------------------------------------------------------------------------
GET http://{{host}}/vtag/user/info
Authorization: Bearer {{vtag_token}}
Content-Type: application/json



### --------------------------------------------------------------------------------------------------------------------
POST http://{{host}}/vtag/user/token
Content-Type: application/json

{
    "username": "84365819777",
    "password": "test"
}

> {%
client.test("Request executed successfully", function() {
  var token = response.body.data.token;
  print(token)
  client.global.set("vtag_token", token)
});
%}


### --------------------------------------------------------------------------------------------------------------------
POST http://{{host}}/vtag/user/token
Content-Type: application/json

{"username": "duclm22", "password": "invalid password"}

### {"code": 1, "message": "Some error!"}


### --------------------------------------------------------------------------------------------------------------------
POST http://{{host}}/vtag/user/otp/reset
Content-Type: application/json

{"type": "phone", "value": "0365819777"}

### {"code": 0, "message": "Created OTP successfully!", "data": {"otp": "123456", "expire": "2020-12-31 12:59:59"}}


### --------------------------------------------------------------------------------------------------------------------
POST http://{{host}}/vtag/user/otp/reset
Content-Type: application/json

{"type": "phone", "value": "0365819778"}

### {"code": 1, "message": "Some error!"}


### --------------------------------------------------------------------------------------------------------------------
POST http://{{host}}/vtag/user/notification
Content-Type: application/json

{"fcm_token": "0365818777"}

### {"code": 0, "message": "Some message!"}
### {"code": 1, "message": "Some error!"}


### --------------------------------------------------------------------------------------------------------------------
POST http://{{host}}/vtag/user/password
Content-Type: application/json
Authorization: Bearer {{vtag_token}}

{
    "old_password": "test",
    "new_password": "abcdef"
}

### {"code": 0, "message": "Some message!"}


### --------------------------------------------------------------------------------------------------------------------
POST http://{{host}}/vtag/user/password
Content-Type: application/json
Authorization: Bearer {{vtag_token}}

{
    "old_password": "abcdef",
    "new_password": "test"
}

### {"code": 1, "message": "Some error!"}



### --------------------------------------------------------------------------------------------------------------------
POST http://{{host}}/vtag/user/password/reset
Content-Type: application/json

{
    "otp": "123456",
    "phone": "0365819777",
    "new_password": "new_password"
}
