### --------------------------------------------------------------------------------------------------------------------
POST http://{{host}}/vtag/user/otp/register
Content-Type: application/json

{"type": "phone", "value": "84365819777"}



### Register new account -----------------------------------------------------------------------------------------------
POST http://{{host}}/vtag/user/register
Content-Type: application/json

{"phone": "0365819778"}

### check token --------------------------------------------------------------------------------------------------------
GET http://{{host}}/vtag/user/info
Authorization: Bearer {{vtag_token}}



### --------------------------------------------------------------------------------------------------------------------
POST http://{{host}}/vtag/user/token
Content-Type: application/json

{
    "username": "84365731814",
    "password": "Test1aA@"
}

> {%
client.test("Request executed successfully", function() {
  var token = response.body.data.token;
  print(token)
  client.global.set("vtag_token", token)
});
%}


### --------------------------------------------------------------------------------------------------------------------
POST http://{{host}}/vtag/user/token
Content-Type: application/json

{"username": "duclm22", "password": "invalid password"}

### {"code": 1, "message": "Some error!"}


### --------------------------------------------------------------------------------------------------------------------
POST http://{{host}}/vtag/user/otp/reset
Content-Type: application/json

{"type": "phone", "value": "0365819777"}



### --------------------------------------------------------------------------------------------------------------------
POST http://{{host}}/vtag/user/otp/reset
Content-Type: application/json

{"type": "phone", "value": "0365819778"}



### --------------------------------------------------------------------------------------------------------------------
POST http://{{host}}/vtag/user/notification
Authorization: Bearer {{vtag_token}}
Content-Type: application/json

{"fcm_token": "abc"}



### --------------------------------------------------------------------------------------------------------------------
POST http://{{host}}/vtag/user/password
Authorization: Bearer {{vtag_token}}
Content-Type: application/json

{
    "old_password": "test",
    "new_password": "abcdef"
}



### --------------------------------------------------------------------------------------------------------------------
POST http://{{host}}/vtag/user/password
Content-Type: application/json
Authorization: Bearer {{vtag_token}}

{
    "old_password": "abcdef",
    "new_password": "test"
}

### --------------------------------------------------------------------------------------------------------------------
POST http://{{host}}/vtag/user/password/reset
Content-Type: application/json

{
    "otp": "123456",
    "phone": "0365819777",
    "new_password": "new_password"
}
