###
POST http://localhost:8080/vtag/device/test
Content-Type: application/json

{
    "token": "284a3628cddb31",
    "radio": "nbiot",
    "address": 1,
    "mcc": 452,
    "mnc": 4,
    "cells": [
        {"lac": 43300, "cid": 75430933, "psc": 0}
    ],
    "wifi": []
}


### wifi cell
POST http://localhost:8080/vtag/device/test
Content-Type: application/json

{
    "Type": "DWFC",
    "Conn": "nbiot",
    "Cell": [
        {"CID": 75430933, "LAC": 43300, "MCC": 452, "MNC": 4, "SS": -93},
        {"CID": 75430933, "LAC": 43300, "MCC": 452, "MNC": 4, "SS": -93}
    ],
    "APs": [
        {"SS": -59, "MAC": "E6:A6:B2:0F:82:73"},
        {"SS": -66, "MAC": "3C:7C:3F:40:B4:68"},
        {"SS": -70, "MAC": "C0:4A:00:0C:8B:A2"},
        {"SS": -78, "MAC": "7C:8B:CA:DF:9D:E4"},
        {"SS": -83, "MAC": "D4:2C:3D:29:18:0D"},
        {"SS": -89, "MAC": "3C:15:FB:42:DE:0C"},
        {"SS": -91, "MAC": "10:2F:6B:BB:1C:33"}
    ]
}


### GPS
POST http://localhost:8080/vtag/device/test
Content-Type: application/json

{
    "Type": "DPOS",
    "Ver": "7.2",
    "Conn": "nbiot",
    "Lat": 21.068147769858182,
    "Lon": 105.81206979664238,
    "TS": "2021-03-24 14-33-23"
}

### SOS
POST http://localhost:8080/vtag/device/test
Content-Type: application/json

{
    "Type": "DSOS",
    "Conn": "nbiot",
    "Cell": [{"CID": 75430933, "LAC": 43300, "MCC": 452, "MNC": 4, "SS": -95}],
    "APs": [
        {"SS": -58, "MAC": "B0:95:75:6B:B0:B7"},
        {"SS": -67, "MAC": "A0:F3:C1:CF:32:F6"},
        {"SS": -79, "MAC": "C0:A5:DD:14:67:B2"},
        {"SS": -84, "MAC": "00:1D:0F:CB:35:84"},
        {"SS": -89, "MAC": "68:FF:7B:21:9F:50"},
        {"SS": -90, "MAC": "AC:84:C6:B4:40:5A"},
        {"SS": -92, "MAC": "9C:65:EE:BB:68:AF"},
        {"SS": -94, "MAC": "B4:EE:B4:61:2F:FA"},
        {"SS": -95, "MAC": "D8:07:B6:EE:6F:C3"}
    ]
}
