### --------------------------------------------------------------------------------------------------------------------
POST http://{{host}}/vtag/user/otp/register
Content-Type: application/json

{"type": "phone", "value": "0365818777"}

### {"code": 0, "message": "Created OTP successfully!", "data": {"otp": "123456", "expire": "2020-12-31 12:59:59"}}
### {"code": 1, "message": "Some error!"}


### Register new account -----------------------------------------------------------------------------------------------
POST http://{{host}}/vtag/user/register
Content-Type: application/json

{"phone": "0365819777", "password": "test"}

### {"code": 0, "message": "Created user successfully!"}
### {"code": 1, "message": "Some error!"}


### --------------------------------------------------------------------------------------------------------------------
POST http://{{host}}/vtag/user/token
Content-Type: application/json

{"username": "duclm22", "password": "test"}

### {"code": 0, "message": "Get token successfully!", "data": {"token": "13143534-1231423-1425"}}


### --------------------------------------------------------------------------------------------------------------------
POST http://{{host}}/vtag/user/token
Content-Type: application/json

{"username": "duclm22", "password": "invalid password"}

### {"code": 1, "message": "Some error!"}


### --------------------------------------------------------------------------------------------------------------------
POST http://{{host}}/vtag/user/otp/reset
Content-Type: application/json

{"type": "phone", "value": "0365818777"}

### {"code": 0, "message": "Created OTP successfully!", "data": {"otp": "123456", "expire": "2020-12-31 12:59:59"}}
### {"code": 1, "message": "Some error!"}


### --------------------------------------------------------------------------------------------------------------------
POST http://{{host}}/vtag/user/notification
Content-Type: application/json

{"fcm_token": "0365818777"}

### {"code": 0, "message": "Some message!"}
### {"code": 1, "message": "Some error!"}


### --------------------------------------------------------------------------------------------------------------------
POST http://{{host}}/vtag/user/password
Content-Type: application/json
Authorization: Bearer

{"old_password": "abcd", "new_password": "abcdef"}

### {"code": 0, "message": "Some message!"}
### {"code": 1, "message": "Some error!"}
