### --------------------------------------------------------------------------------------------------------------------
POST http://{{host}}/vtag/device/pair
Authorization: Bearer {{vtag_token}}
Content-Type: application/json

{
    "name": "PairDevice",
    "platform_id": "d86c8f22-e026-440f-bc17-ca77cee811c2"
}

### 200: {"code": 0, "message": "Paired device successfully!"}
### 502: {"code": 1, "message": "Couldn't pair device!"}



### --------------------------------------------------------------------------------------------------------------------
GET http://{{host}}/vtag/device/list
Content-Type: application/json
Authorization: Bearer {{vtag_token}}



### --------------------------------------------------------------------------------------------------------------------
POST http://{{host}}/vtag/device/route
Content-Type: application/json
Authorization: Bearer {{vtag_token}}

{
    "device_id": "9a2612a6-4f5f-4fa2-84f8-6cc00d63a12f",
    "from": 1617438512412,
    "to": 1617439512412
}


