### --------------------------------------------------------------------------------------------------------------------
POST http://{{host}}:8080/vtag/user/otp
Content-Type: application/json

{"type": "email", "value": "duclm22@viettel.com.vn"}



### --------------------------------------------------------------------------------------------------------------------
POST http://{{host}}:8080/vtag/user/otp
Content-Type: application/json

{"type": "phone", "value": "0365819777"}



### Register new account -----------------------------------------------------------------------------------------------
POST http://{{host}}:8080/vtag/user/register
Content-Type: multipart/form-data; boundary=WebAppBoundary

--WebAppBoundary
Content-Disposition: form-data; name="avatar"; filename="avatar.png"

< ./avatar.png
--WebAppBoundary--
Content-Disposition: form-data; name="avatar"

--WebAppBoundary--



### --------------------------------------------------------------------------------------------------------------------
POST http://{{host}}:8080/vtag/user/token
Content-Type: application/json

{"username": "duclm22", "password": "test"}



### --------------------------------------------------------------------------------------------------------------------
POST http://{{host}}:8080/vtag/user/token
Content-Type: application/json

{"username": "duclm22", "password": "invalid password"}



### --------------------------------------------------------------------------------------------------------------------
POST http://{{host}}:8080/vtag/device
Authorization: Bearer c5b430b2-db82-42e0-9c8b-4ed5c97817d9
Content-Type: application/json


