spring:
  main:
    web-application-type: reactive
  webflux:
    base-path: /vtag

server:
  port: 8080

vtag:
  otp:
    length: 6
  platform:
    address: https://api.iotcloud.com.vn:4438
    grant_type: client_credentials
    client_id: 28e1ffc5-029c-4fa4-b688-6309593d68f0
    client_secret: PBfya2HCR_MiWZPJXenpADKhtp
  storage:
    location: ~/storage/
  mqtt:
    qos: 1
    client-id: vtag-backend
    timeout: 5000

---
spring:
  profiles: dev
  datasource:
    jdbcUrl: jdbc:postgresql://127.0.0.1:5432/postgres?useSSL=false
    driverClassName: org.postgresql.Driver
    username: postgres
    password: 123456
  sms-datasource:
    jdbcUrl: jdbc:mysql://127.0.0.1:3306/smssupport?useSSL=false
    driverClassName: com.mysql.jdbc.Driver
    username: root
    password: 1
vtag:
  mqtt:
    url: tcp://localhost:1883
    topic: test
    username: test
    password: test

---
spring:
  profiles: test
  datasource:
    jdbcUrl: jdbc:mysql://127.0.0.1:30306/fm?useSSL=false
    driverClassName: org.postgresql.Driver
    username: root
    password: 1
  sms-datasource:
    jdbcUrl: jdbc:mysql://127.0.0.1:3306/smssupport?useSSL=false
    driverClassName: com.mysql.jdbc.Driver
    username: root
    password: 1

---
spring:
  profiles: production
  datasource:
    jdbcUrl: jdbc:mysql://10.60.88.22:9999/fm?useSSL=false
    driverClassName: org.postgresql.Driver
    username: ems
    password: 123456aA@
  sms-datasource:
    url: jdbc:mysql://10.60.19.18:3306/smssupport?useSSL=false
    driverClassName: com.mysql.jdbc.Driver
    username: hrmuser
    password: 123456a@
