spring:
  main:
    web-application-type: reactive
  webflux:
    base-path: /vtag
  datasource:
    driverClassName: org.postgresql.Driver
  sms-datasource:
    driverClassName: com.mysql.jdbc.Driver

server:
  port: 8080

vtag:
  otp:
    length: 6
    allowed-chars: "0123456789"
  platform:
    address: http://10.55.123.124:4438
    grant-type: client_credentials
    client-id: 28e1ffc5-029c-4fa4-b688-6309593d68f0
    client-secret: PBfya2HCR_MiWZPJXenpADKhtp
  storage:
    location: ~/storage/
  mqtt:
    qos: 1
    client-id: vtag-backend
    timeout: 5000
  unwired:
      token:

---
spring:
  profiles: dev
  datasource:
    jdbcUrl: jdbc:postgresql://127.0.0.1:5432/postgres?useSSL=false
    username: postgres
    password: 1
  sms-datasource:
    jdbcUrl: jdbc:mysql://127.0.0.1:3306/smssupport?useSSL=false
    username: root
    password: 1
vtag:
  mqtt:
    url: tcp://127.0.0.1:1883
    topic: test
    username: username
    password: password

---
spring:
  profiles: test
  datasource:
    jdbcUrl: jdbc:mysql://127.0.0.1:30306/fm?useSSL=false
    username: root
    password: 1
  sms-datasource:
    jdbcUrl: jdbc:mysql://127.0.0.1:3306/smssupport?useSSL=false
    username: root
    password: 1

---
spring:
  profiles: production
  datasource:
    jdbcUrl: jdbc:postgresql://10.55.121.73:5432/postgres?useSSL=false
    username: postgres
    password: 1
  sms-datasource:
    jdbcUrl: jdbc:mysql://10.60.19.18:3306/smssupport?useSSL=false
    username: hrmuser
    password: 123456a@
vtag:
  mqtt:
    enable: false
    url: tcp://10.55.123.124:4439
    topic: messages/0b00307f-b802-486a-93ef-ba204e631764/data
    username: username
    password: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpYXQiOjE2MTczMzA1OTIsImlzcyI6IjJhNjFmNjYzLTgzMDItNGNhMS1hM2ZmLWJiOTUwYTMzNDk3MSIsInN1YiI6IjJhNjFmNjYzLTgzMDItNGNhMS1hM2ZmLWJiOTUwYTMzNDk3MSIsInR5cGUiOjJ9.4keTJ6QA1oaBwyeZibrXAsOlrLLBPW3XAhdrcpwr0Gs
