spring:
  main:
    web-application-type: reactive
  webflux:
    base-path: /vtag
  datasource:
    driverClassName: org.postgresql.Driver
  sms-datasource:
    driverClassName: com.mysql.jdbc.Driver

server:
  port: 8080

vtag:
  platform:
    base-url: https://api.iotcloud.com.vn:4438
    grant-type: client_credentials
    client-id: 9221f93a-58b6-40c5-8dc5-1bd6ab0a4897
    client-secret: 90pd2Ot8LZURZtUB8XL69cOdB9
  mqtt:
    qos: 1
    client-id: vtag-backend
    timeout: 5000
  unwired:
    token: 284a3628cddb31
    base-url: https://ap1.unwiredlabs.com
    uri: /v2/process.php
  otp:
    length: 6
    allowed-chars: "0123456789"
  storage:
    location: ~/storage/
  proxy:
    host: 10.55.123.98
    port: 3128

---
spring:
  profiles: dev
  datasource:
    jdbcUrl: jdbc:postgresql://127.0.0.1:5432/postgres?useSSL=false
    username: postgres
    password: 1
  sms-datasource:
    jdbcUrl: jdbc:mysql://127.0.0.1:3306/smssupport?useSSL=false
    username: root
    password: 1
vtag:
  proxy:
    enable: false
  mqtt:
    url: tcp://127.0.0.1:1883
    topic: messages/+/wildcard
    username: username
    password: password
    publisher-client-id: vtag_dev_publisher
    subscriber-client-id: vtag_dev_subscriber

---
spring:
  profiles: test-db
  datasource:
    jdbcUrl: jdbc:postgresql://203.113.138.18:4446/postgres?useSSL=false
    username: postgres
    password: 1
  sms-datasource:
    jdbcUrl: jdbc:mysql://127.0.0.1:3306/smssupport?useSSL=false
    username: root
    password: 1
vtag:
  proxy:
    enable: false
  platform:
    base-url: https://api.iotcloud.com.vn:4438
  mqtt:
    url: tcp://127.0.0.1:1883
    topic: messages/+/wildcard
    username: username
    password: password
    publisher-client-id: vtag_dev_publisher
    subscriber-client-id: vtag_dev_subscriber

---
spring:
  profiles: test
  datasource:
    jdbcUrl: jdbc:postgresql://203.113.138.18:4446/postgres?useSSL=false
    username: postgres
    password: 1
  sms-datasource:
    jdbcUrl: jdbc:mysql://127.0.0.1:3306/smssupport?useSSL=false
    username: root
    password: 1
vtag:
  proxy:
    enable: false
  platform:
    base-url: https://api.iotcloud.com.vn:4438
  mqtt:
    url: tcp://203.113.138.21:4439
    username: vtag_backend_test
    publisher-client-id: vtag_test_publisher
    subscriber-client-id: vtag_test_subscriber
    password: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpYXQiOjE2MTc0MzUxODQsImlzcyI6ImVlMjExNjkwLWQ0ZDktNGZjNS04MTgzLWQ0ZjQyY2Y4OWU2MyIsInN1YiI6ImVlMjExNjkwLWQ0ZDktNGZjNS04MTgzLWQ0ZjQyY2Y4OWU2MyIsInR5cGUiOjJ9.NO8vjM_vdV2vFM93ktIGXMMLdy6WzK_eJrNkWvDNylc

---
spring:
  profiles: production
  datasource:
    jdbcUrl: jdbc:postgresql://10.55.121.73:4446/postgres?useSSL=false
    username: postgres
    password: 1
  sms-datasource:
    jdbcUrl: jdbc:mysql://10.60.19.18:3306/smssupport?useSSL=false
    username: hrmuser
    password: 123456a@
vtag:
  proxy:
    enable: true
  platform:
    base-url: https://api.iotcloud.com.vn:4438
  mqtt:
    enable: false
    url: tcp://10.55.123.124:4439
    username: vtag_backend_production
    publisher-client-id: vtag_production_publisher
    subscriber-client-id: vtag_production_subscriber
    password: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpYXQiOjE2MTc0MzUxODQsImlzcyI6ImVlMjExNjkwLWQ0ZDktNGZjNS04MTgzLWQ0ZjQyY2Y4OWU2MyIsInN1YiI6ImVlMjExNjkwLWQ0ZDktNGZjNS04MTgzLWQ0ZjQyY2Y4OWU2MyIsInR5cGUiOjJ9.NO8vjM_vdV2vFM93ktIGXMMLdy6WzK_eJrNkWvDNylc
  unwired:
    token: 284a3628cddb31
