version: "3.9"
services:
  postgres:
    container_name: postgres
    image: postgres:lastest
    environment:
      POSTGRES_PASSWORD: 1
      TZ: Asia/Ho_Chi_Minh
    volumes:
      - ~/data/postgres:/var/lib/postgresql/data
      - ~/be/init/:/docker-entrypoint-initdb.d
    ports:
      - 5432:5432

  mysql:
    container_name: mysql
    image: mysql:lastest
    environment:
      MYSQL_ROOT_PASSWORD: 1
      TZ: Asia/Ho_Chi_Minh
    volumes:
      - ~/data/mysql:/var/lib/mysql
    ports:
      - 3306:3306
