version: "3.9"
services:
# docker run -dp 5432:5432 -e POSTGRES_PASSWORD=1 -e TZ=GMT+7 -v /home/vht/be/init/:/docker-entrypoint-initdb.d
#  -v ~/be/data/postgres:/var/lib/postgres/data --name postgres postgres:latest
  postgres:
    container_name: postgres
    image: postgres:lastest
    environment:
      POSTGRES_PASSWORD: 1
      TZ: Asia/Ho_Chi_Minh
    volumes:
      - ~/data/postgres:/var/lib/postgresql/data
      - ~/be/init/:/docker-entrypoint-initdb.d
    ports:
      - 4446:5432

  mysql:
    container_name: mysql
    image: mysql:lastest
    environment:
      MYSQL_ROOT_PASSWORD: 1
      TZ: Asia/Ho_Chi_Minh
    volumes:
      - ~/data/mysql:/var/lib/mysql
    ports:
      - 3306:3306
